export const EMAIL_AUTH_SIGN_IN = 'EMAIL_AUTH_SIGN_IN';
export const EMAIL_AUTH_SIGN_IN_FAILURE = 'EMAIL_AUTH_SIGN_IN_FAILURE';
export const EMAIL_AUTH_SIGN_IN_SUCCESS = 'EMAIL_AUTH_SIGN_IN_SUCCESS';

export const EMAIL_AUTH_SIGN_UP = 'EMAIL_AUTH_SIGN_UP';
export const EMAIL_AUTH_SIGN_UP_FAILURE = 'EMAIL_AUTH_SIGN_UP_FAILURE';
export const EMAIL_AUTH_SIGN_UP_SUCCESS = 'EMAIL_AUTH_SIGN_UP_SUCCESS';

export const SOCIAL_AUTH = 'SOCIAL_AUTH';
export const SOCIAL_AUTH_FAILURE = 'SOCIAL_AUTH_FAILURE';
export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';
