export const EMAIL_AUTH_SIGN_IN = 'EMAIL_AUTH_SIGN_IN';
export const EMAIL_AUTH_SIGN_IN_FAILURE = 'EMAIL_AUTH_SIGN_IN_FAILURE';
export const EMAIL_AUTH_SIGN_IN_SUCCESS = 'EMAIL_AUTH_SIGN_IN_SUCCESS';

export const SEND_EMAIL_VERIFICATION_LINK = 'SEND_EMAIL_VERIFICATION_LINK';
export const SEND_EMAIL_VERIFICATION_LINK_FAILURE = 'SEND_EMAIL_VERIFICATION_LINK_FAILURE';
export const SEND_EMAIL_VERIFICATION_LINK_SUCCESS = 'SEND_EMAIL_VERIFICATION_LINK_SUCCESS';

export const EMAIL_AUTH_SIGN_UP = 'EMAIL_AUTH_SIGN_UP';
export const EMAIL_AUTH_SIGN_UP_FAILURE = 'EMAIL_AUTH_SIGN_UP_FAILURE';
export const EMAIL_AUTH_SIGN_UP_SUCCESS = 'EMAIL_AUTH_SIGN_UP_SUCCESS';

export const FACEBOOK_AUTH = 'FACEBOOK_AUTH';
export const FACEBOOK_AUTH_FAILURE = 'FACEBOOK_AUTH_FAILURE';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';

export const GOOGLE_AUTH = 'GOOGLE_AUTH';
export const GOOGLE_AUTH_FAILURE = 'GOOGLE_AUTH_FAILURE';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';

export const SAVE_USER_ID = 'SAVE_USER_ID';
export const SAVE_AUTH_FULL_NAME = 'SAVE_AUTH_FULL_NAME';
export const SAVE_AUTH_EMAIL = 'SAVE_AUTH_EMAIL';
export const SAVE_AUTH_PASSWORD = 'SAVE_AUTH_PASSWORD';
export const TOGGLE_AUTH_PASSWORD_MODAL = 'TOGGLE_AUTH_PASSWORD_MODAL';
export const SAVE_AUTH_TYPE = 'SAVE_AUTH_TYPE';
export const SAVE_USER_TYPE = 'SAVE_USER_TYPE';
export const SAVE_PICTURE_URL = 'SAVE_PICTURE_URL';
